<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Form DCT</title>
<? $this->headLink()->appendStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/2.3.2/css/bootstrap.min.css') ?>
<?  $this->headLink()->appendStylesheet($this->baseUrl().'/public/css/bootstrap-responsive.css') ?>
<? $this->headLink()->appendStylesheet($this->baseUrl().'/public/css/index.css')?>

<? echo $this->headLink(); ?>
</head>
<body>